version: '3.8'
services:
  postgres:
    container_name: todo-app-database
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=justuser
      - POSTGRES_PASSWORD=justpwd
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
volumes:
  postgres: